# generated by datamodel-codegen:
#   filename:  implementation_tracker.json
#   timestamp: 2026-06-07T03:21:51+00:00

from __future__ import annotations
from typing import Literal, Annotated
from pydantic import BaseModel, ConfigDict, Field


ImplementationTrackerTitle = Annotated[
    str,
    Field(pattern=r"^Implementation \d+ Tracker$")
]


class Metadata(BaseModel):
  model_config = ConfigDict(extra="forbid")

  document_id: Annotated[str, Field(pattern=r"^implementation_tracker_\d+\.json$")]
  title: ImplementationTrackerTitle
  purpose: Literal["This file tracks an implementation plan."]
  source_format: Literal["json"]
  document_authority: Literal["operational_state"]


class TrackerItem(BaseModel):
  model_config = ConfigDict(extra="forbid")

  date: str
  seam: str
  agent: str
  change: str
  evidence: str
  status: Literal[
      "proposed",
      "active",
      "blocked",
      "reviewing",
      "complete"
  ]


class Blocker(BaseModel):
  model_config = ConfigDict(extra="forbid")

  blocker: str
  boundary: str
  owner_agent: str
  resolution: str


class ImplementationTracker(BaseModel):
  model_config = ConfigDict(extra="forbid")

  metadata: Metadata
  status: str
  state: Literal[
      "proposed",
      "active",
      "blocked",
      "reviewing",
      "complete"
  ]
  tracker: list[TrackerItem]
  blockers: list[Blocker]
  closeout_notes: list[str]
