# generated by datamodel-codegen:
#   filename:  archive_manager.agent.json
#   timestamp: 2026-06-18T12:43:27+00:00

from __future__ import annotations
from typing import Literal
from pydantic import BaseModel, ConfigDict, Field

from harness.agents.agent_contract import (
  AgentInputPolicyEntry,
  AgentOutputPolicyEntry,
  ProviderId,
)


class Metadata(BaseModel):
  model_config = ConfigDict(extra="forbid")

  id: Literal["archive_manager.agent.json"]
  agent_name: Literal["Archive Manager"]
  document_authority: Literal["global_harness"]


class ReportSummary(BaseModel):
  model_config = ConfigDict(extra="forbid")

  basis: str
  truthfulness_check: str


class SourceCoverage(BaseModel):
  model_config = ConfigDict(extra="forbid")

  basis: str
  truthfulness_check: str


class ArchiveRecord(BaseModel):
  model_config = ConfigDict(extra="forbid")

  record_id: str
  record_type: str
  claim: str
  basis: str
  limits: str
  truthfulness_check: str


class SupportingArtifactReferences(BaseModel):
  model_config = ConfigDict(extra="forbid")

  artifact_path: str
  source_run: str
  basis: str
  limits: str
  truthfulness_check: str


class SourceRun(BaseModel):
  model_config = ConfigDict(extra="forbid")

  run_id: str
  task: str
  git_commit: str
  worktree_state: str


class FutureCitationUse(BaseModel):
  model_config = ConfigDict(extra="forbid")

  pm_may_cite_for: str
  pm_must_not_cite_for: str
  truthfulness_check: str


class ArtifactTruthfulness(BaseModel):
  model_config = ConfigDict(extra="forbid")

  compiled_runtime_artifacts: str
  output_policy_artifacts: str
  raw_provider_artifacts: str
  validation_artifacts: str
  ledger_artifacts: str
  archive_records: str
  non_runtime_templates: str


class ReportDerivationLenses(BaseModel):
  model_config = ConfigDict(extra="forbid")

  report_summary: ReportSummary
  source_coverage: SourceCoverage
  archive_record: ArchiveRecord
  supporting_artifact_references: SupportingArtifactReferences
  source_run: SourceRun
  future_citation_use: FutureCitationUse
  artifact_truthfulness: ArtifactTruthfulness


class InstructionContract(BaseModel):
  model_config = ConfigDict(extra="forbid")

  role: str
  posture: str
  objective: str
  operating_context: list[str]
  archive_manager_conduct: list[str]
  report_derivation_lenses: ReportDerivationLenses


class ArchiveManagerOutputPolicyEntry(AgentOutputPolicyEntry):
  output_id: Literal["archive_manager_report"]
  required: bool
  schema_ref: Literal["../contracts/ArchiveManagerReport.schema.json"]


class ArchiveManager(BaseModel):
  model_config = ConfigDict(extra="forbid")

  field_schema: str = Field(..., alias='$schema')
  metadata: Metadata
  provider: ProviderId
  model: str = Field(min_length=1)
  instruction_contract: InstructionContract
  agent_input_policy: list[AgentInputPolicyEntry]
  agent_output_policy: list[ArchiveManagerOutputPolicyEntry]
