# generated by datamodel-codegen:
#   filename:  archive_manager_report.example.json
#   timestamp: 2026-06-17T17:18:10+00:00

from __future__ import annotations
from typing import Literal
from pydantic import BaseModel, ConfigDict, Field, model_validator

EvidenceClaims = Literal[
  "agent_output_was_parsed",
  "agent_output_matched_schema",
  "bounded_archive_record_was_emitted"
]

SourceCoverageDisposition = Literal[
  "used",
  "inspected_insufficient",
  "inspected_not_relevant",
  "inspected_contradictory",
  "missing",
  "invalid",
  "not_required_for_task",
]


class Metadata(BaseModel):
  model_config = ConfigDict(extra="forbid")

  document_id: Literal["archive_manager_report.json"]
  title: Literal["Archive Manager Report"]
  source_format: Literal["json"]
  document_authority: Literal["generated_artifact"]
  evidentiary_authority: Literal["output_policy_artifact"]
  evidence_claims: list[EvidenceClaims]


class StaticContextPacket(BaseModel):
  model_config = ConfigDict(extra="forbid")

  consumed: bool
  disposition: SourceCoverageDisposition
  basis: list[str] = Field(min_length=1)

  @model_validator(mode="after")
  def enforce_consumed_disposition_consistency(self):
    consumed_dispositions = {
      "used",
      "inspected_insufficient",
      "inspected_not_relevant",
      "inspected_contradictory",
    }
    expected_consumed = self.disposition in consumed_dispositions
    if self.consumed != expected_consumed:
      raise ValueError(
        f"disposition={self.disposition!r} requires consumed={expected_consumed}."
      )

    return self


class Task(BaseModel):
  model_config = ConfigDict(extra="forbid")

  consumed: bool
  disposition: SourceCoverageDisposition
  basis: list[str] = Field(min_length=1)

  @model_validator(mode="after")
  def enforce_consumed_disposition_consistency(self):
    consumed_dispositions = {
      "used",
      "inspected_insufficient",
      "inspected_not_relevant",
      "inspected_contradictory",
    }
    expected_consumed = self.disposition in consumed_dispositions
    if self.consumed != expected_consumed:
      raise ValueError(
        f"disposition={self.disposition!r} requires consumed={expected_consumed}."
      )

    return self


class RepoSnapshotPacket(BaseModel):
  model_config = ConfigDict(extra="forbid")

  consumed: bool
  disposition: SourceCoverageDisposition
  basis: list[str] = Field(min_length=1)

  @model_validator(mode="after")
  def enforce_consumed_disposition_consistency(self):
    consumed_dispositions = {
      "used",
      "inspected_insufficient",
      "inspected_not_relevant",
      "inspected_contradictory",
    }
    expected_consumed = self.disposition in consumed_dispositions
    if self.consumed != expected_consumed:
      raise ValueError(
        f"disposition={self.disposition!r} requires consumed={expected_consumed}."
      )

    return self


class GitContext(BaseModel):
  model_config = ConfigDict(extra="forbid")

  consumed: bool
  disposition: SourceCoverageDisposition
  basis: list[str] = Field(min_length=1)

  @model_validator(mode="after")
  def enforce_consumed_disposition_consistency(self):
    consumed_dispositions = {
      "used",
      "inspected_insufficient",
      "inspected_not_relevant",
      "inspected_contradictory",
    }
    expected_consumed = self.disposition in consumed_dispositions
    if self.consumed != expected_consumed:
      raise ValueError(
        f"disposition={self.disposition!r} requires consumed={expected_consumed}."
      )

    return self


class ReportSourceCoverage(BaseModel):
  model_config = ConfigDict(extra="forbid")

  static_context_packet: StaticContextPacket
  task: Task
  repo_snapshot_packet: RepoSnapshotPacket
  git_context: GitContext


class SourceRun(BaseModel):
  model_config = ConfigDict(extra="forbid")

  run_id: str
  task: str
  git_commit: str
  worktree_state: str


class SupportingArtifactReference(BaseModel):
  model_config = ConfigDict(extra="forbid")

  artifact_path: str
  source_run: SourceRun
  basis: list[str]
  limits: list[str]


class FutureCitationUse(BaseModel):
  model_config = ConfigDict(extra="forbid")

  pm_may_cite_for: list[str]
  pm_must_not_cite_for: list[str]


class ArchiveRecord(BaseModel):
  model_config = ConfigDict(extra="forbid")

  record_id: str
  record_type: str
  claim: str
  supporting_artifact_references: list[SupportingArtifactReference]
  basis: list[str]
  limits: list[str]
  future_citation_use: FutureCitationUse


class ArchiveManagerReport(BaseModel):
  model_config = ConfigDict(extra="forbid")

  metadata: Metadata
  report_summary: str
  report_source_coverage: ReportSourceCoverage
  archive_record: ArchiveRecord
