# generated by datamodel-codegen:
#   filename:  project_manager_report.json
#   timestamp: 2026-06-08T15:20:58+00:00

from __future__ import annotations
from typing import Literal
from pydantic import BaseModel, ConfigDict, Field, model_validator

EvidenceClaims = Literal[
  "agent_output_was_parsed",
  "agent_output_matched_schema",
  "bounded_report_claim_was_emitted"
]

SourceCoverageDisposition = Literal[
  "used",
  "inspected_insufficient",
  "inspected_not_relevant",
  "inspected_contradictory",
  "missing",
  "invalid",
  "not_required_for_task",
]


class Metadata(BaseModel):
  model_config = ConfigDict(extra="forbid")

  document_id: Literal["project_manager_report.json"]
  title: Literal["Project Manager Report"]
  source_format: Literal["json"]
  document_authority: Literal["runtime_evidence"]
  evidentiary_authority: Literal["output_policy_artifact"]
  evidence_claims: list[EvidenceClaims]


class ReportSourceCoverageEntry(BaseModel):
  model_config = ConfigDict(extra="forbid")

  consumed: bool
  disposition: SourceCoverageDisposition
  basis: list[str] = Field(min_length=1)

  @model_validator(mode="after")
  def enforce_consumed_disposition_consistency(self):
    consumed_dispositions = {
      "used",
      "inspected_insufficient",
      "inspected_not_relevant",
      "inspected_contradictory",
    }
    expected_consumed = self.disposition in consumed_dispositions
    if self.consumed != expected_consumed:
      raise ValueError(
        f"disposition={self.disposition!r} requires consumed={expected_consumed}."
      )

    return self


class ReportSourceCoverage(BaseModel):
  model_config = ConfigDict(extra="forbid")

  static_context_packet: ReportSourceCoverageEntry
  task: ReportSourceCoverageEntry
  repo_snapshot_packet: ReportSourceCoverageEntry
  git_context: ReportSourceCoverageEntry


class DriftDetection(BaseModel):
  model_config = ConfigDict(extra="forbid")

  drift_detected: bool
  description: str | None


class TrajectoryReview(BaseModel):
  model_config = ConfigDict(extra="forbid")

  current_posture: str
  thesis_attractor: str
  drift_detection: DriftDetection
  structural_tension: str


class ProofFrontier(BaseModel):
  model_config = ConfigDict(extra="forbid")

  constraint_conflicts: list[str]
  dominant_tension_justification: str | None

  blocked: bool
  blocking_reason: str | None
  missing_basis: list[str]

  next_admissible_transformation: str | None
  affected_surfaces: list[str] | None
  non_affected_surfaces: list[str] | None
  stop_conditions: list[str] | None
  authority_constraints: list[str]


class ProjectManagerReport(BaseModel):
  model_config = ConfigDict(extra="forbid")

  metadata: Metadata
  report_status: Literal[
    "admissible",
    "admissibility_blocked",
    "rejected",
    "needs_clarification",
  ]
  report_summary: str
  report_source_coverage: ReportSourceCoverage
  trajectory_review: TrajectoryReview
  proof_frontier: ProofFrontier

  @model_validator(mode="after")
  def enforce_report_truth_table(self):
    coverage = self.report_source_coverage
    required_coverage = {
      "static_context_packet": coverage.static_context_packet,
      "task": coverage.task,
    }

    for source_id, entry in required_coverage.items():
      if not entry.consumed:
        raise ValueError(
          f"report_source_coverage.{source_id}.consumed must be true."
        )

    frontier = self.proof_frontier

    # Requested-transition admissibility and next-frontier openness are separate axes.
    # A report may block the requested transition while still naming a next admissible transformation.
    if self.report_status == "admissible":
      if frontier.blocked:
        raise ValueError(
          "admissible reports must have proof_frontier.blocked=false."
        )

      if frontier.blocking_reason is not None:
        raise ValueError(
          "admissible reports must not include blocking_reason."
        )

      if frontier.missing_basis:
        raise ValueError(
          "admissible reports must not include missing_basis."
        )

      if frontier.constraint_conflicts:
        raise ValueError(
          "admissible reports must not include constraint_conflicts."
        )

      if frontier.next_admissible_transformation is None:
        raise ValueError(
          "admissible reports require next_admissible_transformation."
        )

      return self

    # All non-admissible statuses block the requested transition.
    # This does NOT mean the frontier is closed. They may still name a next admissible move.
    if not frontier.blocked:
      raise ValueError(
        f"{self.report_status} reports require proof_frontier.blocked=true."
      )

    if not frontier.blocking_reason:
      raise ValueError(
        f"{self.report_status} reports require blocking_reason."
      )

    if self.report_status == "admissibility_blocked":
      if not frontier.missing_basis:
        raise ValueError(
          "admissibility_blocked reports require missing_basis naming the absent basis, context, evidence, or authority."
        )

      if frontier.constraint_conflicts:
        raise ValueError(
          "admissibility_blocked reports must not include established constraint_conflicts; use rejected when a constraint conflict is established."
        )

    if self.report_status == "needs_clarification":
      if not frontier.missing_basis:
        raise ValueError(
          "needs_clarification reports require missing_basis naming what the user must clarify."
        )

      if frontier.constraint_conflicts:
        raise ValueError(
          "needs_clarification reports must not include established constraint_conflicts; use rejected when a constraint conflict is established."
        )

    if self.report_status == "rejected":
      if not frontier.constraint_conflicts:
        raise ValueError(
          "rejected reports require constraint_conflicts naming the violated boundary."
        )

    return self
