# generated by datamodel-codegen:
#   filename:  project_manager_report.json
#   timestamp: 2026-06-08T15:20:58+00:00

from __future__ import annotations
from typing import Literal
from pydantic import BaseModel, ConfigDict, Field, model_validator


class Metadata(BaseModel):
  model_config = ConfigDict(extra="forbid")

  document_id: Literal["project_manager_report.json"]
  title: Literal["Project Manager Report"]
  source_format: Literal["json"]
  document_authority: Literal["output_policy_artifact"]


SourceCoverageDisposition = Literal[
  "used",
  "inspected_insufficient",
  "inspected_not_relevant",
  "inspected_contradictory",
  "missing",
  "invalid",
  "not_required_for_task",
]


class ReportSourceCoverageEntry(BaseModel):
  model_config = ConfigDict(extra="forbid")

  consumed: bool = Field(
    description=(
      "Whether the Project Manager materially reviewed the source. This does "
      "not indicate that the source is binding authority."
    )
  )
  disposition: SourceCoverageDisposition = Field(
    description=(
      "How the Project Manager handled this source in this report. 'used' "
      "means the source materially supported a report claim, not that it is "
      "binding authority. 'inspected_insufficient' means the source was "
      "reviewed but did not substantiate the requested claim family. "
      "'inspected_not_relevant' means it was reviewed but was outside the "
      "task. 'inspected_contradictory' means it contradicted the requested "
      "claim family without independently determining report_status. "
      "'missing' and 'invalid' describe source availability or validity, not "
      "authority. 'not_required_for_task' means the source was unnecessary "
      "for the current task."
    )
  )
  basis: list[str] = Field(
    min_length=1,
    description=(
      "Concrete free-text explanation of the disposition. It may name a "
      "governance evidence_class or valid_claim_family when useful, but the "
      "text is descriptive and is not parsed for validation."
    ),
  )

  @model_validator(mode="after")
  def enforce_consumed_disposition_consistency(self):
    consumed_dispositions = {
      "used",
      "inspected_insufficient",
      "inspected_not_relevant",
      "inspected_contradictory",
    }
    expected_consumed = self.disposition in consumed_dispositions
    if self.consumed != expected_consumed:
      raise ValueError(
        f"disposition={self.disposition!r} requires consumed={expected_consumed}."
      )

    return self


class ReportSourceCoverage(BaseModel):
  model_config = ConfigDict(extra="forbid")

  static_context_packet: ReportSourceCoverageEntry
  task: ReportSourceCoverageEntry
  repo_snapshot_packet: ReportSourceCoverageEntry
  git_context: ReportSourceCoverageEntry


class DriftDetection(BaseModel):
  model_config = ConfigDict(extra="forbid")

  drift_detected: bool
  description: str | None


class TrajectoryReview(BaseModel):
  model_config = ConfigDict(extra="forbid")

  current_posture: str
  thesis_attractor: str
  drift_detection: DriftDetection
  structural_tension: str


class ProofFrontier(BaseModel):
  model_config = ConfigDict(extra="forbid")

  constraint_conflicts: list[str]
  dominant_tension_justification: str | None

  blocked: bool
  blocking_reason: str | None
  missing_basis: list[str]

  next_admissible_transformation: str | None
  affected_surfaces: list[str] | None
  non_affected_surfaces: list[str] | None
  stop_conditions: list[str] | None
  authority_constraints: list[str]


class ProjectManagerReport(BaseModel):
  model_config = ConfigDict(extra="forbid")

  metadata: Metadata
  report_status: Literal[
    "admissible",
    "admissibility_blocked",
    "rejected",
    "needs_clarification",
  ]
  report_summary: str
  report_source_coverage: ReportSourceCoverage
  trajectory_review: TrajectoryReview
  proof_frontier: ProofFrontier

  @model_validator(mode="after")
  def enforce_report_truth_table(self):
    coverage = self.report_source_coverage
    required_coverage = {
      "static_context_packet": coverage.static_context_packet,
      "task": coverage.task,
    }

    for source_id, entry in required_coverage.items():
      if not entry.consumed:
        raise ValueError(
          f"report_source_coverage.{source_id}.consumed must be true."
        )

    frontier = self.proof_frontier

    # Disposition and frontier openness are separate axes.
    if frontier.blocked:
      if not frontier.blocking_reason:
        raise ValueError("blocked proof_frontier requires blocking_reason.")
    elif frontier.blocking_reason is not None:
      raise ValueError(
        "unblocked proof_frontier must not include blocking_reason."
      )

    if self.report_status == "admissible":
      if frontier.blocked:
        raise ValueError(
          "admissible reports must have proof_frontier.blocked=false."
        )

      if frontier.blocking_reason is not None:
        raise ValueError(
          "admissible reports must not include blocking_reason."
        )

      if frontier.missing_basis:
        raise ValueError(
          "admissible reports must not include missing_basis."
        )

      if frontier.constraint_conflicts:
        raise ValueError(
          "admissible reports must not include constraint_conflicts."
        )

      if frontier.next_admissible_transformation is None:
        raise ValueError(
          "admissible reports require next_admissible_transformation."
        )

      return self

    if self.report_status == "admissibility_blocked":
      if not frontier.missing_basis:
        raise ValueError(
          "admissibility_blocked reports require missing_basis naming the absent basis, context, evidence, or authority."
        )

      if frontier.constraint_conflicts:
        raise ValueError(
          "admissibility_blocked reports must not include established constraint_conflicts; use rejected when a constraint conflict is established."
        )

    if self.report_status == "needs_clarification":
      if not frontier.missing_basis:
        raise ValueError(
          "needs_clarification reports require missing_basis naming what the user must clarify."
        )

      if frontier.constraint_conflicts:
        raise ValueError(
          "needs_clarification reports must not include established constraint_conflicts; use rejected when a constraint conflict is established."
        )

    if self.report_status == "rejected":
      if not frontier.constraint_conflicts:
        raise ValueError(
          "rejected reports require constraint_conflicts naming the violated boundary."
        )

    return self
