# generated by datamodel-codegen:
#   filename:  governance_primitives.json
#   timestamp: 2026-06-09T21:07:19+00:00

from __future__ import annotations
from typing import Literal
from pydantic import BaseModel, ConfigDict, Field

BindingAuthority = Literal[
    "global_harness",
    "harness_target",
    "runtime_policy",
    "operational_state"
]

RuntimeEvidence = Literal[
  "compiled_runtime_artifact",
  "output_policy_artifact",
  "raw_provider_artifact",
  "validation_artifact",
  "ledger_artifact",
  "archive_record"
]

CompiledRuntimeClaim = Literal[
  "context_was_compiled",
  "payload_was_constructed"
]

OutputPolicyClaim = Literal[
  "agent_output_was_parsed",
  "agent_output_matched_schema",
  "bounded_report_claim_was_emitted"
]

RawProviderClaim = Literal[
  "provider_returned_response",
  "audit_trace_exists"
]

ValidationClaim = Literal[
  "schema_validation_passed_or_failed",
  "probe_result_recorded"
]

LedgerClaim = Literal[
  "api_call_was_recorded",
  "route_invocation_was_recorded",
  "token_usage_was_recorded"
]

ArchiveClaim = Literal[
  "bounded_historical_claim_was_preserved",
  "future_reports_may_cite_record_without_reconstructing_raw_artifacts"
]

AgentContracts = Literal[
  "project_manager",
  "planning_manager",
  "review_manager",
  "red_team_manager",
  "implementation_manager",
  "archive_manager",
  "worker_adapter"
  ]

ApprovalSensitiveSurfaces = Literal[
  "global_harness",
  "agent_contracts",
  "output_policies",
  "runtime_orchestration",
  "tool_and_worker_surface",
  "provider_or_api_behavior",
  "compatibility_commitments"
  ]

RuntimeEvidence = Literal[
  "compiled_runtime_artifact",
  "output_policy_artifact",
  "raw_provider_artifact",
  "validation_artifact",
  "ledger_artifact",
  "archive_record"
]

class Metadata(BaseModel):
  model_config = ConfigDict(extra="forbid")

  document_id: Literal["governance_primitives.json"]
  title: Literal["Governance Primitives"]
  context: Literal["Global governance for the CLI harness. These primitives govern agent operation, execution boundaries, runtime artifact semantics, and authority separation in every target repository the harness is placed inside and invoked against."]
  purpose: Literal["Define and delineate global harness-level invariants from harness target repository boundaries that every project workflow must respect."]
  source_format: Literal["json"]
  document_authority: Literal["global_harness"]


class DocumentAuthorityClasses(BaseModel):
  model_config = ConfigDict(extra="forbid")

  binding_authority: list[BindingAuthority]

class ValidClaimFamilies(BaseModel):
  model_config = ConfigDict(extra="forbid")

  compiled_runtime_artifact: list[CompiledRuntimeClaim]
  output_policy_artifact: list[OutputPolicyClaim]
  raw_provider_artifact: list[RawProviderClaim]
  validation_artifact: list[ValidationClaim]
  ledger_artifact: list[LedgerClaim]
  archive_record: list[ArchiveClaim]


class EvidenceClasses(BaseModel):
  model_config = ConfigDict(extra="forbid")

  runtime_evidence: list[DerivedRuntimeArtifact]
  valid_claim_families: ValidClaimFamilies
  boundary_rule: Literal[
    "Evidence classes may substantiate bounded runtime, validation, provenance, or historical claims. They do not create project authority, amend project intent, authorize route changes, or override binding authority."
  ]


class GovernancePrimitives(BaseModel):
  model_config = ConfigDict(extra="forbid")

  schema_ref: str = Field(..., alias='$schema')
  metadata: Metadata
  document_authority_classes: DocumentAuthorityClasses
  agent_contracts: list[AgentContracts]
  approval_sensitive_surfaces: list[ApprovalSensitiveSurfaces] = []
  evidence_classes: EvidenceClasses
